# Dictionary of plots to make by-hand using SimpleNtupler in CompareData.py or CompareDataMC.py

import numpy as np
import math as math
MAKEPLOTLIST = {
        'vertex_m':{
            'titles':'Vertex Constrained Dimuon Mass;m(#mu^{+}#mu^{-}) [GeV];Events',
            'bins':[20000,0,20000],
            'var':'vertex_m',
            'log':{'x':False,'y':True},
            'rebin':50,
            'lims':{'min':50,'max':3500,'reset':True},
            'overflow':False,
            'underflow':False,
            },
        'vertex_m_log':{
            'titles':'Vertex Constrained Dimuon Mass;m(#mu^{+}#mu^{-}) [GeV];Events',
            'bins':[500,np.logspace(np.log10(50),np.log10(10000),501)],
            'var':'vertex_m',
            'log':{'x':True,'y':True},
            'rebin':10,
            'lims':{'min':50,'max':3500,'reset':True},
            'overflow':False,
            'underflow':False,
            },
        'muon_pt':{
            'titles':'Muon p_{T};muon p_{T} [GeV];N(muons)',
            'bins':[5000,0,5000],
            'var':'lep_pt',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':0,'max':2000,'reset':True},
            'overflow':False,
            'underflow':False,
            },
        'muon_pz':{
            'titles':'Muon p_{Z};muon p_{Z} [GeV];N(muons)',
            'bins':[5000,0,5000],
            'var':'lep_pz',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':0,'max':2000,'reset':True},
            'overflow':False,
            'underflow':False,
            },
        'muon_p':{
            'titles':'Muon P;muon p [GeV];N(muons)',
            'bins':[5000,0,5000],
            'var':'lep_p',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':0,'max':2000,'reset':True},
            'overflow':False,
            'underflow':False,
            },
        'muon_eta':{
            'titles':'Muon #eta;muon #eta;N(muons)',
            'bins':[240,-2.4,2.4],
            'var':'lep_eta',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':-2.4,'max':2.4,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'muon_phi':{
            'titles':'Muon #phi;muon #phi;N(muons)',
            'bins':[100,-math.pi,math.pi],
            'var':'lep_phi',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':-math.pi,'max':math.pi,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'num_pv':{
            'titles':'Number of Primary Vertices;N(primary vertices);Events',
            'bins':[100,0,100],
            'var':'nvertices',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':100,'reset':False},
            'overflow':True,
            'underflow':False,
            },
        'muon_num_v_pix_hits':{
            'titles':'Number of Valid Pixel Hits;N(valid pixel hits);N(muons)',
            'bins':[13,0,13],
            'var':'lep_glb_numberOfValidPixelHits',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':13,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'muon_num_v_trk_lays':{
            'titles':'Number of Valid Tracker Layers;N(valid tracker layers);N(muons)',
            'bins':[20,0,20],
            'var':'lep_glb_numberOfValidTrackerLayers',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':20,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'muon_num_v_glb_mu_hits':{
            'titles':'Number of Valid Global Track Muon Hits;N(valid global track muon hits);N(muons)',
            'bins':[61,0,61],
            'var':'lep_glb_numberOfValidMuonHits',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':61,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'muon_num_v_tuneP_mu_hits':{
            'titles':'Number of Valid tuneP Track Muon Hits;N(valid tuneP track muon hits);N(muons)',
            'bins':[61,0,61],
            'var':'lep_tuneP_numberOfValidMuonHits',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':61,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'muon_num_match_mu_st':{
            'titles':'Number of Matched Muon Stations;N(matched muon stations);N(muons)',
            'bins':[7,0,7],
            'var':'lep_numberOfMatchedStations',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':7,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'muon_trk_rel_iso':{
            'titles':'Relative Tracker Isolation;#Sigma p_{T} / trk. p_{T};N(muons)',
            'bins':[50,0,1],
            'var':'lep_sumPt/lep_tk_pt',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':1,'reset':False},
            'overflow':True,
            'underflow':False,
            },
        'dimuon_vertex_ndof':{
            'titles':'Dimuon Vertex N(dof);vertex N(dof);Events',
            'bins':[100,0,100],
            'var':'vertex_ndof',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':100,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_vertex_p':{
            'titles':'Dimuon Vertex Probability;Probability;Events',
            'bins':[100,0,1],
            'var':'vertex_p',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':1,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_vertex_chi2':{
            'titles':'Dimuon Vertex #chi^{2}/dof;vertex #chi^{2}/dof;Events',
            'bins':[300,0,30],
            'var':'vertex_chi2',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':0,'max':30,'reset':False},
            'overflow':True,
            'underflow':False,
            },
        'muon_rel_pt_err':{
            'titles':'Relative p_{T} ;#sigma(p_{T}) / p_{T};N(muons)',
            'bins':[50,0,1],
            'var':'lep_sumPt/lep_tk_pt',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':1,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'muon_rel_pt_err_log':{
            'titles':'Relative p_{T} ;#sigma(p_{T}) / p_{T};N(muons)',
            'bins':[500,np.logspace(np.log10(0.005),np.log10(10),501)],
            'var':'lep_pt_err/lep_pt',
            'log':{'x':True,'y':True},
            'rebin':10,
            'lims':{'min':0.005,'max':1,'reset':False},
            'overflow':True,
            'underflow':True,
            },
        'muon_dB':{
            'titles':'Transverse Impact Parameter;d_{xy} [cm];N(muons)',
            'bins':[100,0,1],
            'var':'lep_dB',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':0,'max':1,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'muon_dB_log':{
            'titles':'Transverse Impact Parameter;d_{xy} [cm];N(muons)',
            'bins':[100,np.logspace(-6,2,101)],
            'var':'lep_dB',
            'log':{'x':True,'y':True},
            'rebin':1,
            'lims':{'min':pow(10,-6),'max':pow(10,2),'reset':False},
            'overflow':True,
            'underflow':True,
            },
        'dimuon_delta_pt':{
            'titles':'Dimuon |p_{T}^{1}| - |p_{T}^{2}|;|p_{T}^{1}| - |p_{T}^{2}| [GeV];Events',
            'bins':[400,-200,200],
            'var':'fabs(lep_pt[0])-fabs(lep_pt[1])',
            'log':{'x':False,'y':True},
            'rebin':4,
            'lims':{'min':-100,'max':100,'reset':True},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_delta_p':{
            'titles':'Dimuon |p^{1}| - |p^{2}|;|p^{1}| - |p^{2}| [GeV];Events',
            'bins':[1000,-500,500],
            'var':'fabs(lep_p[0])-fabs(lep_p[1])',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':-100,'max':100,'reset':True},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_phi':{
            'titles':'Dimuon #phi;dimuon #phi;Events',
            'bins':[600,-math.pi,math.pi],
            'var':'dil_phi',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':-math.pi,'max':math.pi,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_rap':{
            'titles':'Dimuon Rapidity;dimuon rapidity y;Events',
            'bins':[600,-6,6],
            'var':'dil_rap',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':-6,'max':6,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_eta':{
            'titles':'Dimuon #eta;dimuon #eta;Events',
            'bins':[600,-6,6],
            'var':'dil_eta',
            'log':{'x':False,'y':True},
            'rebin':10,
            'lims':{'min':-6,'max':6,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_cos_angle':{
            'titles':'Dimuon cos(#alpha);cos(#alpha);Events',
            'bins':[100,-1,1],
            'var':'cos_angle',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':-1,'max':1,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_cs_costheta':{
            'titles':'Dimuon Collins-Soper cos(#theta);Collins-Soper cos(#theta);Events',
            'bins':[100,-1,1],
            'var':'cos_cs',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':-1,'max':1,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_cs_phi':{
            'titles':'Dimuon Collins-Soper #phi);Collins-Soper #phi;Events',
            'bins':[100,-math.pi,math.pi],
            'var':'phi_cs',
            'log':{'x':False,'y':True},
            'rebin':1,
            'lims':{'min':-math.pi,'max':math.pi,'reset':False},
            'overflow':False,
            'underflow':False,
            },
        'dimuon_pt':{
            'titles':'Dimuon p_{T};dimuon p_{T} [GeV];Events',
            'bins':[2000,0,2000],
            'var':'dil_pt',
            'log':{'x':False,'y':True},
            'rebin':20,
            'lims':{'min':0,'max':1000,'reset':True},
            'overflow':False,
            'underflow':False,
            },

        }

